### ISSUE TITLE
Diferenças entre $_SESSION['user']['name'] e $session->name

### ISSUE THREAD

**Issue by eborguezao** [osians/Session#1]
Oi, sei que aqui não é o local apropriado para a dúvida, sinta-se a vontade para excluí-la.
Qual vantagem além do armazenamento de dados em sessão para o nativo e o uso da biblioteca? Alguma vantagem de segurança, criptografia, roubo de sessão? Não entendi a diferença.

Desculpe a "leiguisse".

**Comment by osians** [comment]
Em verdade sao todas as vantagens que voce citou. Mas a maior vantagem é o encapsulamento que a Orientação a Objetos permite. Isso organiza o código em um único lugar, permite validar os dados antes de registrar na sessão , facilita debug, testes unitários (PHPUnit). O uso de interfaces permite padronizar o código de uma forma que vc pode usar em qualquer outro projeto facilmente. Além do mais uma biblioteca é fácil ser extendida para adicionar novas funcionalidades, sem modificar o código original. O roubo de sessão também é evitado na classe (hijacking). No dia a dia pode ser solicitado a voce gravar os dados de sessão no banco de dados, isso é mais fácil de ser alterado em um método dentro de uma biblioteca , fica mais fácil! Bom, espero que isso responda sua pergunta. Fique a vontade para contactar em sans.pds@gmail.com caso tenha dúvidas ainda. Abs

**Comment by eborguezao** [comment]
@osians o que me interessou demais foi a classe (hijacking), então fui buscar conhecimento de OOP e puder ver tudo isso, e seu esclarecimento me confirmou as vantagens, já implementei e testei, agradeço pela sua sapiência e boa vontade.

**Comment by eborguezao** [comment]
Inclui os arquivos SessionInterface.php e Session.php e iniciei a biblioteca com:
$session = new Session(20 * 60);

O que pude observar que após a implementação da biblioteca, em qualquer página do website quando atualizada, no diretório /tmp do servidor um novo arquivo de sessão é criado, se navego pelo site por 100 páginas, 100 arquivos são criados, o que há de errado nisso? Deveria manter apenas um único arquivo pela sessão do navegador do usuário ativo não?

**Comment by osians** [comment]
Então, essa sua dúvida é mais interna ao funcionamento do PHP. Não é algo a se preocupar. Deixa eu tentar explicar.
Quando uma sessão inicia no PHP (session_start()), o sistema interno do PHP vai criar um arquivo na pasta tmp (ou numa pasta definida com a função session_save_path()), com um nome tal como: **sess_0rp4r00elb9q07jhsg**. Esse arquivo ou qualquer outro de sessão é controlado pelo PHP e o ideal é que não tenhamos contato com ele. 

O PHP sabe quando é o momento de deletar esses arquivos, e a exclusão é feita através do **PHP Session Garbage Collector**, a frequência em que a exclusão ocorre é controlada pela configuração "session.gc_maxlifetime" que se encontra no "php.ini" (_nota: por vezes isso pode se encontrar em arquivos especificos, algo com /usr/lib/php5/maxlifetime_), ou ainda o PHP pode resolver se livrar dos arquivos quando você usar a função session_destroy(). 

Agora um pouco da **session_regenerate_id()**, essa função como o nome já diz irá gerar um novo id de sessão a cada chamada ao servidor e possivelmente criar um novo arquivo. É importante criar um novo id de sessão para evitar um ataques como **Hijacking** e **Session Fixation**, onde, um individuo explorando uma vulnerabilidade qualquer pode conseguir acesso ao arquivo de sessão na pasta tmp, e associa-lo a si próprio, ganhando total controle sobre a sessão de um usuário qualquer e a seus dados sensíveis.

Logo, manter 1 único arquivo pode não ser o cenário ideal. E o PHP Garbage Collector se encarrega de realizar a limpeza.

**Comment by eborguezao** [comment]
Oi, agradeço novamente pela sua sapiência e boa vontade, sua explicação foi
esclarecedora e aprendi bastante, sou Júnior e venho estudando bastante,
estou estudando sua biblioteca porque me interesso bastante sobre segurança
de dados e criptografia, e estou me atentando quanto às condições de
corrida do PHP, estou bastante tranquilo em usar o que você disponibilizou
para a comunidade. Desejo saúde e prosperidade em sua vida, paz.

Em dom, 17 de mai de 2020 11:54, Wanderlei Santana <notifications@github.com>
escreveu:
